### ISSUE TITLE
full size detail view doesn't load on mobile device

### ISSUE THREAD

**Issue by githubmonkey** [kc0bfv/autophugo#5]
The detail image doesn't load on my mobile device. (Pixel 2, Chrome) On the chrome device simulator it works well. Any idea what could be the problem? 

![Screenshot_20201123-125734](https://user-images.githubusercontent.com/5363503/99954898-20915980-2d8c-11eb-8dd1-067efc860c4b.png)

**Comment by kc0bfv** [comment]
Sylvia, I have this problem to on my Android under Chrome.  I think I've
tracked it to an interaction between the lightbox and the browser's lazy
loading pieces, which have been a default setting on chrome mobile for a
few months now.

I reported it as a chrome bug, and didn't get too far in trying to track it
down in the lightbox code.  I'll try to do that soon because the chrome bug
has been open for a while and I'm not sure anyone there will close it any
time soon.

Chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1076521&q=Lazy&can=8

**Comment by githubmonkey** [comment]
Thanks for the speedy response!!! I'll keep an eye on your repo for changes.

**Comment by kc0bfv** [comment]
@githubmonkey the old lightbox (poptrox) was not getting updates - not that it was a bug with poptrox - but it seemed like it was maybe time to switch lightboxes anyway.  I switched to a new one, and it doesn't have the same issue.  So - should be fixed in the latest now.

Thanks for motivating me to just solve this, regardless of Chrome bug ;-)
