### ISSUE TITLE
Google Search Console Doesn't Like My Autophugo Pages

### ISSUE THREAD

**Issue by wwone** [kc0bfv/autophugo#50]
Now, I'm not going to ask you to plumb the depths of the deep, dark, Google search system. However, I try to nudge it to process my web pages, in hopes of getting search engine action.

Recently, I received warnings from Google Search Console, indicating that  my new autophugo main pages (index.html) could not be indexed by the search engine, claiming that there is a redirect error (loop? bad redirect?) in them. 

Checking the generated "index.html", I cannot find any redirect code in the file. Does Autophugo create built-in redirect (meta) tags, or any other explicit redirects in its generated HTML?

**Comment by kc0bfv** [comment]
Not that I know of...  And looking in Chrome's network inspection view, I don't see anything either.  Looking at your food page specifically - I don't see anything either.  Is it possible that it's looking for an HTTPS version of your site?  That's a thing Google is doing by default since about 2015/2014, and they're providing preference to https sites.

https://developers.google.com/search/blog/2015/12/indexing-https-pages-by-default

**Comment by wwone** [comment]
Thanks for looking. As I noted, attempting to figure out what the GSC really wants, and how it decides whether a page is "mobile-friendly" or not, is obviously a black art. There is no human you can contact, and the tagging of a page as NOT or (yes) friendly seems to vary with each attempt to have it evaluated.

(One possible reason for their thinking there is a redirect, is the use of a URL like: http://mysite.com/something rather than http://mysite.com/something/index.html. Of course, my sitemap uses the full URL with index.html and everything...)

Anyway, you can close this, as any deeper analysis is far beyond our pay grades.

**Comment by kc0bfv** [comment]
Lol - yeah, it can be a pain.  The lighthouse tools built into Chrome help,
but still...

**Comment by kc0bfv** [comment]
Closing pending future info.
