### ISSUE TITLE
title/description not showing in example sub albums

### ISSUE THREAD

**Issue by githubmonkey** [kc0bfv/autophugo#7]
Also, if the popup contains a description it will be placed below the page threshold where it is hard to discover.

**Comment by kc0bfv** [comment]
Dang, I didn't notice that about the sub album descriptions.  Thanks - will
try to solve soon...

With the lightbox placing the description, is that dependent upon screen
shape and image shape?  I think I saw that happen in some of the cases with
the new lightbox, but I didn't think it was an issue.

It's probably something that could get tuned in the lightbox code...  So I
can try to figure out that one too.

**Comment by githubmonkey** [comment]
The lightbox description being placed below the page fold happens every time the image aspect ratio is less than the screen, i.e., the image is restricted in height. 

![Screenshot 2020-12-02 at 12 58 55](https://user-images.githubusercontent.com/5363503/100864666-f54eee80-349e-11eb-940c-c6f299379b69.png)

See here for my own version with a longer description: [https://photo.rozendallabs.org/demo_for_kc0bfv/](https://photo.rozendallabs.org/demo_for_kc0bfv/), first image.
In my demo site I've changed from a column to a row based layout in the overview. but the lightbox layout is still the same. 

Despite my nagging I love the new lightbox. Thanks for all your work and and especially for your quick turnaround!!

**Comment by kc0bfv** [comment]
I think I got it now...

The text not showing up in subgalleries in the example was just bad filenames, or missing metadata.  The titles were no longer showing up on images anywhere - I accidentally took that out with the new lightbox.

The bottom text...  I scooted it up 20px in CSS.  That should be enough to show a title and the first line of description - I kinda looked at it on an applicable image on a few different screen layouts and orientations - hopefully it does the trick.

I'd actually rather the bottom bar expand up as needed instead of being absolutely positioned as the new lightbox does...  I think I'd need to refactor this to a flexbox view then - and I'm sure I'd run into some other issues then with some of the autosizing javascript this lightbox uses.  In favor of not doing something deeper at this point - I think this solution will work.

**Comment by kc0bfv** [comment]
I'm glad you like the new lightbox!  That was kindof a big change I was hoping folks would think was for the better :-)

**Comment by kc0bfv** [comment]
I like your photos too - I've never been to South Africa and every time I see it in photos or on the news it's not what I expect.  I've been to the Great Sand Dunes in Colorado though - very cool, and your photos show just how out-of-place it really is there.
